[workspace]
resolver = "2"
members = ["host", "methods"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
#opt-level = 3
opt-level = 0

[profile.release]
debug = 1
lto = true
